steps:

  #
  # Run desktop tests
  #
  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

  - label: Run MacOS e2e tests
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-cocoa-11
    env:
      UNITY_VERSION: "2020.3.15f2"
    plugins:
      artifacts#v1.2.0:
        upload:
          - maze_output/*
          - Mazerunner.log
    commands:
      - scripts/ci-run-macos-tests.sh

