steps:

  #
  # Build Windows test fixture
  #
  - label: Build Unity 2020 Windows test fixture
    key: 'windows-2020-fixture'
    timeout_in_minutes: 30
    agents:
      queue: opensource-windows-unity
    env:
      UNITY_VERSION: "2020.3.17f1"
    commands:
      - scripts/ci-build-windows-package.bat
    artifact_paths:
      - features/fixtures/maze_runner/build/Windows-2020.3.17f1.zip

  #
  # Run Windows e2e tests
  #
  - label: Run Windows e2e tests for Unity 2020
    depends_on: 'windows-2020-fixture'
    timeout_in_minutes: 30
    agents:
      queue: opensource-windows-unity
    env:
      UNITY_VERSION: "2020.3.17f1"
    command:
      - scripts/ci-run-windows-tests.bat
